### ISSUE TITLE
pyqt6 - is there a path to releasing this?

### ISSUE THREAD

**Issue by andyfaff** [conda-forge/pyqt-feedstock#124]
### Comment:

I'm wondering if there is a plan for releasing the feedstock to target pyqt6? There isn't a pyqt5 package for `macosx_arm64` on either PyPI or conda-forge. There is a pyqt6 package on PyPI, but I'm hoping it'll make it to conda-forge soon.

I guess that one of the stumbling blocks may be native building of Qt6 and pyqt6. I know that cirrus-ci can be used for native builds for the `macosx_arm64` platform, does conda-forge use cirrus yet?

**Comment by ccordoba12** [comment]
> There isn't a pyqt5 package for macosx_arm64 on either PyPI or conda-forge

Conda-forge packages for PyQt5 are simply called `pyqt`, not `pyqt5`, and there are already packages available for arm64.

> I guess that one of the stumbling blocks may be native building of Qt6 and pyqt6. I know that cirrus-ci can be used for native builds for the macosx_arm64 platform, does conda-forge use cirrus yet?

See conda-forge/qt-main-feedstock#49.

**Comment by andyfaff** [comment]
Sorry, I should've been clearer about where the pain point is here. I maintain a package that uses PyQt for the front end GUI. When people install my package they are installing dependencies using wheels from PyPI or via conda. Now let's say we have a `macosx_arm64` user.

PyQt v5:
- no macosx_arm64 wheels are available
- conda packages are available

PyQt v6:
- macosx_arm64 wheels are available
- no conda packages are available

Thus, there is no version of PyQt for which there are packages available from PyPI AND from conda(-forge). This makes it hard to figure out how to service my user base. Should I focus on wheels to the detriment of the conda-forge package I create or vice-versa?

**Comment by ccordoba12** [comment]
I don't know how to answer your question, but you need to pick one of them for now.

**Comment by maxnoe** [comment]
I think this issue should be reopened in the sense that there still is no conda-forge image for pyqt version 6, independently of whether that would be its own package or just a new major version.

**Comment by maxnoe** [comment]
Note that qt base chose to publish a qt6 package:

https://anaconda.org/conda-forge/qt6-main

https://github.com/conda-forge/qt-main-feedstock/blob/qt6/

**Comment by pgunn** [comment]
Any news on this? QT5 is getting increasingly stale and it doesn't make sense for people to develop new apps targeting it. What's the preferred route for us to use conda-forge to get pyqt6 as a dependency?
