### ISSUE TITLE
Build packages for osx

### ISSUE THREAD

**Issue by ccordoba12** [conda-forge/pyqt-feedstock#2]
Packages couldn't be built in staged-recipes, but there shouldn't be a problem here because we have a matrix build for Travis ;-)

**Comment by ocefpaf** [comment]
Are you doing this now or should I?

**Comment by ccordoba12** [comment]
Please be my guest, I'm finishing Spyder 3.0 right now ;-)

**Comment by ocefpaf** [comment]
> Please be my guest

On it.

> I'm finishing Spyder 3.0 right now ;-)

Yay! :tada:
