### ISSUE TITLE
No Qt4 branch

### ISSUE THREAD

**Issue by gillins** [conda-forge/pyqt-feedstock#20]
Should there be a `qt4` branch in this feedstock? I'm assuming that we will still need to build Qt4 packages for a while. Seems that there is only Qt5 now...

**Comment by ccordoba12** [comment]
Sure, please open it and move the PyQt4 recipes there.

**Comment by jakirkham** [comment]
If we put the branch on commit ( https://github.com/conda-forge/pyqt-feedstock/commit/b5936c0fa35e03024f772a58f4fc53f958efcbf9 ), then it will be the last merge commit that had PyQt 4 before this feedstock was upgraded to PyQt 5.

**Comment by gillins** [comment]
Just done it in #21. I used 257683a (the one after) but the actual recipe files are the same as b5936c0

**Comment by gillins** [comment]
Fixed in #21
