### ISSUE TITLE
pip metadata is not provided

### ISSUE THREAD

**Issue by QuLogic** [conda-forge/pyqt-feedstock#35]
PyQt5 is now available on PyPI, so you can do `pip install pyqt5`. The conda package does not provide the necessary metadata for pip to realize that it is installed, so installing a package that requires it with `pip install` unnecessarily downloads pyqt5 from pypi. For example,
```bash
$ conda create -n test pyqt=5
$ conda activate test
$ pip install pyqt5
```
should not attempt to install pyqt5 again.

**Comment by ccordoba12** [comment]
PRs are welcome. It shouldn't be that hard to come up with one.

**Comment by ocefpaf** [comment]
Closing this b/c this is a deeper issue with `conda` and `pip` interoperability and beyond the scope of the `pyqt` feedstock. With that said a lot changed since the issue was opened and maybe this is no longer a problem.
