### ISSUE TITLE
meshpy missing dependencies gcc and pybind11 with 'conda install meshpy'

### ISSUE THREAD

**Issue by puiseux** [conda-forge/pyqt-feedstock#40]
as i say in the title, when i tried to `$ pip install meshpy`, 
1. i had an error with libstd++.h (??) I dont remember the exact name of .h missing)
2. i installed gcc : `$ conda install gcc`
3.  Then i tried `$ pip uninstall meshpy` followed by `$ pip install meshpy` the installation complains about some `clang++` and `pybind11` missing
4. I installed `pybind11` with `$ conda install pybind11`
5. finally `$ pip uninstall conda` followed by `$ pip install conda` succeeded.
and that's it, meshpy is installed<!--

**Comment by ccordoba12** [comment]
This has nothing to with pyqt, closing.
