### ISSUE TITLE
Dropping gtk2-devel from yum_requirements.txt

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/pyqt-feedstock#47]
As `qt` already [requires `gtk2` from conda-forge]( https://github.com/conda-forge/qt-feedstock/blob/78a5467531dc7c6047d28624e83d6af187ab577e/recipe/meta.yaml#L90 ), there shouldn't be a need to install [`gtk2-devel` with `yum`]( https://github.com/conda-forge/pyqt-feedstock/blob/f84133de2f3f07e331eebc125f758dff2db33234/recipe/yum_requirements.txt#L2 ).

If `pyqt` is linking to `gtk2` directly, it probably is linking to the conda-forge package and then should list it as a dependency. Though this last part would need to be checked.

**Comment by mingwandroid** [comment]
This is a huge dependency just to get sympathetic window styling in QStyle. I'd remove it personally.

**Comment by jakirkham** [comment]
If you'd like to discuss that, feel free to, but this would be a discussion at the `qt` feedstock given that is where this change has already occurred.

**Comment by ccordoba12** [comment]
@mingwandroid, it's only needed at build time, if I remember correctly.

**Comment by jakirkham** [comment]
Currently it is listed as a [`run` dependency]( https://github.com/conda-forge/qt-feedstock/blob/78a5467531dc7c6047d28624e83d6af187ab577e/recipe/meta.yaml#L90 ) as well. Am I understanding you correctly that this shouldn't be the case? If so, would you be willing to raise an issue over at the `qt` feedstock?

**Comment by ocefpaf** [comment]
We should either keep the `yum_requirements.txt` or use a CTD (we are doing both on `qt` BTW due to lack of time to test-debug which one works).

Here I believe we added it to get the tests passing but agree with @mingwandroid, I'm :-1: to add it as an actual requirement. Closing this.
