### ISSUE TITLE
(pyqt) segfault with conda-forge vs defaults

### ISSUE THREAD

**Issue by andyfaff** [conda-forge/pyqt-feedstock#48]
I've been [trying](https://github.com/conda-forge/refnx-feedstock/pull/20) to make a feedstock that depends on qt/pyqt for some of its tests. After some initial hurdles making sure libGL.so was installed I started getting a segfault when pytest was running the GUI tests (the other tests were fine).

After much hair pulling I discovered that the tests pass when I install pyqt5/qt (5.9.2) from `defaults` instead of pyqt5 from conda-forge (5.6.0). I'm not sure what's going on here, but it seems that it would be nice to have a version bump for qt/pyqt.

**Comment by andyfaff** [comment]
For clarity, the tests that were failing where on the Linux 3.6/3.7 builds, macOS and win were fine.

**Comment by ocefpaf** [comment]
We updated both qt and pyqt recently. Closing this but please re-open if you are still experiencing this issue.
