### ISSUE TITLE
Can't launch Spyder; ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

### ISSUE THREAD

**Issue by gravedigger266** [conda-forge/pyqt-feedstock#49]
Issue: after installing Anaconda 3, Spyder won't launch, neither by clicking on the the App icon within Anaconda navigator nor on command line prompt

Environment: Windows 10, Spyder 3.3.3

I installed PyQt5 (seems to be already installed along with Anaconda) and PyQtWebEngine, but still not working. I tried installing PyQtWebKit but I didn't find the right version (I only found 32 bit version but my PC is 64 bit).

Here is the error message on cmd prompt. I receive the same error message on Anaconda navigator.
![image](https://user-images.githubusercontent.com/49758503/56369817-5eb2b880-61fa-11e9-8059-c3a585058ba7.png)

**Comment by ocefpaf** [comment]
There are not enough details here for is to debug this. Please re-open if you are still experiencing this but carefully fill all the info required in the issue template.
