### ISSUE TITLE
`QtGui` import failure on

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/pyqt-feedstock#5]
As per 
- https://github.com/conda-forge/staged-recipes/pull/1655
- https://github.com/conda-forge/qtpy-feedstock/pull/1

I opened #4 to add the check to the recipe tests.

**Comment by astrofrog** [comment]
I'm seeing this too:

https://travis-ci.org/glue-viz/glue-vispy-viewers/builds/162804068

Pinging all maintainers:  @ccordoba12, @mingwandroid, @gillins, @msarahan, @ocefpaf

**Comment by ocefpaf** [comment]
I am travelling this week and the next but I will try to find some time to check this.

**Comment by gillins** [comment]
This happens for me too, but used to work with the `defaults` `pyqt`. Does `qt` need to be rebuilt with session support? See https://riverbankcomputing.com/pipermail/pyqt/2006-October/014594.html

**Comment by ccordoba12** [comment]
Yes, it does.

*Note to self*: These are all the X11 libraries that need to be added to `yum_requirements.txt`

http://doc.qt.io/qt-4.8/requirements-x11.html

**Comment by jakirkham** [comment]
Is this still an issue?

**Comment by ccordoba12** [comment]
Not anymore, closing.
