### ISSUE TITLE
PyQt 5.9 - Error while loading QtDesigner: Symbol not found: _Py_IsInitialized

### ISSUE THREAD

**Issue by hhslepicka** [conda-forge/pyqt-feedstock#53]
Issue:

When loading the QtDesigner with custom python widgets it fails with the following message:
```
dyld: lazy symbol binding failed: Symbol not found: _Py_IsInitialized
  Referenced from: /Users/slepicka/mc/envs/py37/plugins/designer/libpyqt5.dylib
  Expected in: flat namespace

dyld: Symbol not found: _Py_IsInitialized
  Referenced from: /Users/slepicka/mc/envs/py37/plugins/designer/libpyqt5.dylib
  Expected in: flat namespace
```

This was not happening with PyQt 5.6 and Qt 5.6.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/slepicka/mc/envs/py37:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.6             h1de35cc_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
dbus                      1.13.6               h2f22bb5_0    conda-forge
expat                     2.2.5             h0a44026_1002    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
glib                      2.58.3            h2836805_1001    conda-forge
icu                       58.2              h0a44026_1000    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
libcxx                    8.0.0                         2    conda-forge
libcxxabi                 8.0.0                         2    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
libpng                    1.6.37               h2573ce8_0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
openssl                   1.1.1b               h01d97ff_2    conda-forge
pcre                      8.41              h0a44026_1003    conda-forge
pip                       19.1                     py37_0    conda-forge
pyqt                      5.9.2            py37h2a560b1_0    conda-forge
python                    3.7.3                h0d93f26_0    conda-forge
qt                        5.9.7                h93ee506_1    conda-forge
readline                  7.0               hcfe32e1_1001    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
sip                       4.19.8          py37h0a44026_1000    conda-forge
sqlite                    3.26.0            h1765d9f_1001    conda-forge
tk                        8.6.9             ha441bb4_1001    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
zlib                      1.2.11            h1de35cc_1004    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : py37
    active env location : /Users/slepicka/mc/envs/py37
            shell level : 1
       user config file : /Users/slepicka/.condarc
 populated config files : /Users/slepicka/.condarc
          conda version : 4.5.11
    conda-build version : 3.0.19
         python version : 3.6.7.final.0
       base environment : /Users/slepicka/mc  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/slepicka/mc/pkgs
                          /Users/slepicka/.conda/pkgs
       envs directories : /Users/slepicka/mc/envs
                          /Users/slepicka/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.11 requests/2.12.4 CPython/3.6.7 Darwin/17.7.0 OSX/10.13.6
                UID:GID : 1918637911:1704612529
             netrc file : None
           offline mode : False
```
</details>

**Comment by hhslepicka** [comment]
@ccordoba12 @mingwandroid can it be that the fix to avoid the static Python is resulting in a Designer Plugin that was not linked against the shared library provided?

**Comment by ccordoba12** [comment]
You probably need to add again what you did before because the recipe for 5.9 is not an improvement over the 5.6 one, but it was taken directly from Anaconda.

**Comment by hhslepicka** [comment]
@ccordoba12 I’m not sure if I understood what you said correctly.
Do you mean the patch that I had on the old PR to link against the python shared library?

**Comment by ccordoba12** [comment]
Yes, that's what I meant. Sorry if I was not clear enough.

**Comment by hhslepicka** [comment]
I was just confirming to be sure...
I will pyt a PR soon.

**Comment by ocefpaf** [comment]
The xref'ed PR was close. Is this no longer an issue? Can we close it?

**Comment by hhslepicka** [comment]
It is still an issue. At least for who uses the designer plugin. PR was closed as the solution was not accepted so it is better to wait for an official patch from maintainers. (my 2cents)

**Comment by ocefpaf** [comment]
> It is still an issue. At least for who uses the designer plugin.

Can you past the conda list from that environment?

> PR was closed as the solution was not accepted so it is better to wait for an official patch from maintainers. (my 2cents)

I'll look into the PR but maybe those who close could chime in here.

**Comment by ccordoba12** [comment]
> I'll look into the PR but maybe those who close could chime in here.

https://github.com/conda-forge/pyqt-feedstock/pull/54#discussion_r285350107

**Comment by ccordoba12** [comment]
The author himself closed the PR.

**Comment by hhslepicka** [comment]
@ocefpaf the conda list is at the beginning of this issue.
And @ccordoba12 is correct. I closed the PR that I opened with the proposed fix.

**Comment by ocefpaf** [comment]
@hhslepicka maybe

> @ocefpaf the conda list is at the beginning of this issue.

That was from 10 days ago and we have new packages.

> And @ccordoba12 is correct. I closed the PR that I opened with the proposed fix.

Looks like we need an alternative fix b/c that one is a no-no according to @isuruf. But before we try to fix it please try again with the new packages.

**Comment by hhslepicka** [comment]
@ocefpaf do you mind to point me to the release notes of this new package or the version of it?
I am currently using a similar fix at the one at this PR to build a local PyQt against qt (from source) using Anaconda & Python. So far no weird issues and crashes as reported by @isuruf but I do understand the risks of mixing shared and static of a library.

I would like to understand why Python was switched to static linking (which is the root of this and other issues around the Anaconda ecosystem) but that is something that I need to study and look for the answer.

**Comment by hhslepicka** [comment]
@ocefpaf the latest pyqt package is from 16 days ago so I was at the latest by the time of this issue.
https://anaconda.org/conda-forge/pyqt/files

**Comment by hhslepicka** [comment]
Any lucky from someone to find a proper fix for it?
The fix that I proposed at #54 worked for me and I used it without problems for a bit more than a month (I am no longer using it since I needed to move to a newer version of Qt & PyQt).

**Comment by klauer** [comment]
I'm also experiencing this on OSX, with the designer failing to load the pyqt plugin.

The only fix I've found so far is reverting to a very old pyqt5 through anaconda (specifically, `pyqt-5.6.0-py37h8210e8a_7.tar.bz2`), which doesn't seem to be a good long-term solution.

**Comment by hhslepicka** [comment]
@conda-forge/pyqt ideas?

**Comment by isuruf** [comment]
Are these plugins loaded as an extension or are they loaded by qt designer only?

**Comment by hhslepicka** [comment]
Designer only...

**Comment by isuruf** [comment]
Then, we can make `plugins/designer/libpyqt5.dylib` link to `libpython` and keep the rest as is. I don't know how to do this though.

**Comment by hhslepicka** [comment]
My old PR was doing this... the one you mentioned that would cause a conflict... 
Since that is not loaded by Python I think there is no problem into merging it.
Do you mind to take another look with this new information in mind?

**Comment by isuruf** [comment]
@hhslepicka, doesn't that PR make the python extensions link to `libpython.so` as well?

**Comment by hhslepicka** [comment]
@isuruf which extensions are you concerned about? I was running with the fix on PR 54 for a while.

**Comment by isuruf** [comment]
Any library in `lib/python3.7/site-packages/PyQt5`

**Comment by hhslepicka** [comment]
They don't link against `libpython.so`.
The only one that cursed plugin.

**Comment by hhslepicka** [comment]
To be fair... Only the QtDesigner and QMLScene will link to `libpython.so`.
Here is the proof: https://github.com/baoboa/pyqt5/search?q=PYSHLIB&unscoped_q=PYSHLIB

**Comment by isuruf** [comment]
Indeed. conda-build log shows
```
   INFO (pyqt,plugins/designer/libpyqt5.so): Needed DSO lib/libpython2.7.so.1.0 found in conda-forge::python-2.7.15-h5a48372_1009
   INFO (pyqt,plugins/PyQt5/libpyqt5qmlplugin.so): Needed DSO lib/libpython2.7.so.1.0 found in conda-forge::python-2.7.15-h5a48372_1009
```
