### ISSUE TITLE
5.9.2 Produces "black" renders using Mayavi

### ISSUE THREAD

**Issue by patricksnape** [conda-forge/pyqt-feedstock#56]
As per this issue mentioned here:

https://github.com/enthought/mayavi/issues/595#issuecomment-386097374

It seems that 5.9.x doesn't play well with OSX. Looks like perhaps >5.10.2 fixes this issue. I know it's not very productive to just request a new build as pyqt is extremely difficult to get building correctly but just to highlight this may be a "known" issue until we release a new build.

**Comment by patricksnape** [comment]
The effort here is required before this can be solved:

https://github.com/conda-forge/qt-feedstock/pull/110

Which is much appreciated!

**Comment by jschueller** [comment]
outdated, retry with 5.12

**Comment by patricksnape** [comment]
Just to confirm that everything seems fine now with 5.12+
