### ISSUE TITLE
Add Qt / PyQt5 for 5.10+

### ISSUE THREAD

**Issue by leofang** [conda-forge/pyqt-feedstock#58]
Now v5.13 of Qt/PyQt is already out, but on conda-forge it still stays at v5.9. Is it possible to provide packages with newer versions?

Cross-post: ContinuumIO/anaconda-issues#11183

**Comment by ocefpaf** [comment]
Sure! PRs to add them are welcomed!

**Comment by leofang** [comment]
Perhaps it's better to wait for conda-forge/qt-feedstock#110.

**Comment by leofang** [comment]
My PR #61 was closed. Waiting for #59.

**Comment by leofang** [comment]
#61 is reopened. Building for Linux and OS X successes. Waiting for resolving build failure on Windows.
