### ISSUE TITLE
Feature request: Add QtCharts

### ISSUE THREAD

**Issue by mathiasrabe** [conda-forge/pyqt-feedstock#74]
Hi, I think it would be amazing to add QtCharts to the PyQt package of Conda-Forge. At the moment it is just available with PIP. The Package is called PyQtChart there.

https://doc.qt.io/qt-5/qtcharts-index.html

**Comment by mathiasrabe** [comment]
Thanks for the adding QTCharts and sorry for reopening such an old topic.

But I still can't find and install QtCharts. I'm using Miniconda3 (64 Bit - latest version) together with PyCharm on Windows. I've added conda-forge and I can install pyqt from it. But PyCharm is still complaining that it can't find PyQt5.QtChart?!

**Comment by stanislasgrare** [comment]
2023. Same problem. I can install PyQt5 with conda BUT cannot use QtChart "ImportError: cannot import name 'QtChart' from 'PyQt5' ".

Why isn't QtChart included with conda with works when using pip ?

**Comment by jakirkham** [comment]
@stanislasgrare could you please raise a new issue and fill out the info requested in the issue template?
