### ISSUE TITLE
update to version 5.15.0

### ISSUE THREAD

**Issue by mtsolmn** [conda-forge/pyqt-feedstock#85]
Issue: Hi, requesting an update to the new release of pyqt5. Thank you in advance.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by syamajala** [comment]
I would also like this.

**Comment by cbrnr** [comment]
See also #98.

**Comment by CAM-Gerlach** [comment]
The feedstock is now on 5.15.x; can this be closed now?
