### ISSUE TITLE
Issue with PyQt4 from conda-forge

### ISSUE THREAD

**Issue by astrofrog** [conda-forge/pyqt-feedstock#9]
The following minimal example:

https://github.com/astrofrog/debug-pyqt4-defaults/blob/master/.travis.yml

Results in the following failure:

```
$ python -c 'from qtpy import QtGui, QtWidgets'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/qtpy/QtGui.py", line 22, in <module>
    from PyQt4.Qt import QKeySequence, QTextCursor
ImportError: cannot import name QKeySequence
```

This doesn't happen if I don't add the conda-forge channel.

Travis build log: https://travis-ci.org/astrofrog/debug-pyqt4-defaults/builds/183749370

Any idea what could be causing this?

**Comment by ccordoba12** [comment]
This seems more of an error in qtpy instead of one in the Qt package per se.

However, I don't have time to investigate this further.

**Comment by ocefpaf** [comment]
@astrofrog has that worked before? I tested with `pyqt4` from `defaults` and could not get it to work :confused:
